version: '3.9'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:6.7.2
    ports:
      - "3000:3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data: {}
