global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "agents-monitoring"
    metrics_path: /metrics
    static_configs:
      - targets: ["docker.for.mac.localhost:1224"]
