global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9000"]
  - job_name: "node-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-app:1224"]
